version: "3.9"
services:
  crafty-bot:
    build: .
    container_name: crafty-bot
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./bot:/app
      - ./config:/app/config
    environment:
      DISCORD_TOKEN: "Token Goes Here"
      CRAFTY_CONFIG: "/app/config/config.yaml"
