# Discord bot token from https://discord.com/developers/applications
discord_token: null

crafty:
  # Base URL of your Crafty Controller instance
  base_url: "https://localhost:8443"

  # === OPTION A: Use static bearer token (works even with 2FA enabled) ===
  # Get a token using curl/xh:
  #   xh -A bearer -a "$token" GET https://localhost:8443/api/v2/servers
  # bearer_token: "PASTE_YOUR_TOKEN_HERE"
  # Not Test (unknown if it works)

  # === OPTION B: Use username/password (only if 2FA is DISABLED) ===
  username: "admin"
  password: "password"

  # Disable SSL check if Crafty uses self-signed certs
  verify_ssl: false

# How often (seconds) the bot refreshes channel names
update_interval: 300

# Discord category to contain server status channels
category_name: "Crafty Servers"

# Who is allowed to run commands
allowed_user_ids:
  - 123456789012345678 # replace with your Discord user ID(s)
allowed_role_names:
  - "CraftyAdmin" # replace with role(s) allowed to run commands

# Map friendly names to Crafty server names or IDs
servers:
  #Fredly Name:Server UUID
  example: "UUID"
